[workspace]
resolver = "2"
members = ["acktor", "acktor-derive", "acktor-macros"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
authors = ["Chao Gu"]
license = "MIT"
repository = "https://github.com/asymmetry/acktor"
categories = ["asynchronous"]
keywords = ["actor", "async"]

[workspace.dependencies]
acktor = { version = "1.0", path = "./acktor" }
acktor-derive = { version = "1.0", path = "./acktor-derive" }
acktor-macros = { version = "1.0", path = "./acktor-macros" }
