// This file is @generated by prost-build.
/// A message which is used to send a message to a remote actor and wait for a response.
/// The remote actor should response with the given tag.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Send {
    /// The index of the recipient actor in the remote process.
    #[prost(uint64, tag = "1")]
    pub actor_id: u64,
    /// The message to be sent.
    #[prost(bytes = "bytes", tag = "2")]
    pub message: ::prost::bytes::Bytes,
    /// The tag to be used in the reply.
    #[prost(uint64, tag = "3")]
    pub tag: u64,
}
/// A message which is used to send a message to a remote actor without expecting a
/// response.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DoSend {
    /// The index of the recipient actor in the remote process.
    #[prost(uint64, tag = "1")]
    pub actor_id: u64,
    /// The message to be sent.
    #[prost(bytes = "bytes", tag = "2")]
    pub message: ::prost::bytes::Bytes,
}
/// A message which is used to reply to a message sent by `Send` command.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reply {
    /// The tag of the message to be replied.
    #[prost(uint64, tag = "1")]
    pub tag: u64,
    /// The message to be sent in the reply.
    #[prost(bytes = "bytes", tag = "2")]
    pub message: ::prost::bytes::Bytes,
}
/// A message which is used to communicate with remote actors.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActorMessage {
    #[prost(oneof = "actor_message::Message", tags = "1, 2, 3")]
    pub message: ::core::option::Option<actor_message::Message>,
}
/// Nested message and enum types in `ActorMessage`.
pub mod actor_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        /// Sends a message to a remote actor and wait for a response.
        #[prost(message, tag = "1")]
        Send(super::Send),
        /// Sends a message to a remote actor without expecting a response.
        #[prost(message, tag = "2")]
        DoSend(super::DoSend),
        /// Replies to a message sent by `Send` command.
        #[prost(message, tag = "3")]
        Reply(super::Reply),
    }
}
