// This file is @generated by prost-build.
/// IPC message.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IpcMessage {
    #[prost(oneof = "ipc_message::Message", tags = "1, 2")]
    pub message: ::core::option::Option<ipc_message::Message>,
}
/// Nested message and enum types in `IpcMessage`.
pub mod ipc_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        /// A message which is used to communicate with remote nodes directly.
        #[prost(message, tag = "1")]
        Node(super::super::node_message::NodeMessage),
        /// A message which is used to communicate with remote actors.
        #[prost(message, tag = "2")]
        Actor(super::super::actor_message::ActorMessage),
    }
}
