// This file is @generated by prost-build.
/// A message which is used to create a new actor in the remote node.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateActor {
    /// The label of the actor.
    #[prost(string, tag = "1")]
    pub label: ::prost::alloc::string::String,
    /// The type of the actor.
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    /// The config of the actor.
    #[prost(string, tag = "3")]
    pub config: ::prost::alloc::string::String,
    /// The tag to be used in the reply.
    #[prost(uint64, tag = "4")]
    pub tag: u64,
}
/// A message which is used to get the index of a remote actor by its label.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetActor {
    /// The tag to be used in the reply.
    #[prost(uint64, tag = "3")]
    pub tag: u64,
    #[prost(oneof = "get_actor::ActorHandle", tags = "1, 2")]
    pub actor_handle: ::core::option::Option<get_actor::ActorHandle>,
}
/// Nested message and enum types in `GetActor`.
pub mod get_actor {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ActorHandle {
        #[prost(uint64, tag = "1")]
        ActorId(u64),
        #[prost(string, tag = "2")]
        Label(::prost::alloc::string::String),
    }
}
/// A message which is used to control the remote nodes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeCommand {
    #[prost(oneof = "node_command::Command", tags = "1, 2")]
    pub command: ::core::option::Option<node_command::Command>,
}
/// Nested message and enum types in `NodeCommand`.
pub mod node_command {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Command {
        /// Creates a new actor in the remote node.
        #[prost(message, tag = "1")]
        CreateActor(super::CreateActor),
        /// Gets the index of a remote actor by its label.
        #[prost(message, tag = "2")]
        GetActor(super::GetActor),
    }
}
/// The result of CreateActor command.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateActorResult {
    /// The tag of the message to be replied.
    #[prost(uint64, tag = "1")]
    pub tag: u64,
    /// The result of the command.
    #[prost(oneof = "create_actor_result::Result", tags = "2, 3")]
    pub result: ::core::option::Option<create_actor_result::Result>,
}
/// Nested message and enum types in `CreateActorResult`.
pub mod create_actor_result {
    /// The result of the command.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        /// The index of the actor.
        #[prost(uint64, tag = "2")]
        Ok(u64),
        /// The error message.
        #[prost(string, tag = "3")]
        Err(::prost::alloc::string::String),
    }
}
/// The result of GetActor command.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetActorResult {
    /// The tag of the message to be replied.
    #[prost(uint64, tag = "1")]
    pub tag: u64,
    /// The result of the command.
    #[prost(oneof = "get_actor_result::Result", tags = "2, 3")]
    pub result: ::core::option::Option<get_actor_result::Result>,
}
/// Nested message and enum types in `GetActorResult`.
pub mod get_actor_result {
    /// The result of the command.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        /// The index of the actor.
        #[prost(uint64, tag = "2")]
        Ok(u64),
        /// The error message.
        #[prost(string, tag = "3")]
        Err(::prost::alloc::string::String),
    }
}
/// A message which is used to reply a node command.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeReply {
    #[prost(oneof = "node_reply::Reply", tags = "1, 2")]
    pub reply: ::core::option::Option<node_reply::Reply>,
}
/// Nested message and enum types in `NodeReply`.
pub mod node_reply {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Reply {
        /// The result of CreateActor command.
        #[prost(message, tag = "1")]
        CreateActor(super::CreateActorResult),
        /// The result of GetActor command.
        #[prost(message, tag = "2")]
        GetActor(super::GetActorResult),
    }
}
/// A message which is used to communicate with remote nodes directly.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeMessage {
    #[prost(oneof = "node_message::Message", tags = "1, 2")]
    pub message: ::core::option::Option<node_message::Message>,
}
/// Nested message and enum types in `NodeMessage`.
pub mod node_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        /// Node command.
        #[prost(message, tag = "1")]
        Command(super::NodeCommand),
        /// Reply of a node command.
        #[prost(message, tag = "2")]
        Reply(super::NodeReply),
    }
}
