// This file is @generated by prost-build.
/// A message which represents a Result type in Rust.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResultMessage {
    #[prost(oneof = "result_message::Result", tags = "1, 2")]
    pub result: ::core::option::Option<result_message::Result>,
}
/// Nested message and enum types in `ResultMessage`.
pub mod result_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        /// The ok message.
        #[prost(bytes, tag = "1")]
        Ok(::prost::bytes::Bytes),
        /// The err message.
        #[prost(string, tag = "2")]
        Err(::prost::alloc::string::String),
    }
}
/// A message which represents an Option type in Rust.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OptionMessage {
    #[prost(bytes = "bytes", optional, tag = "1")]
    pub option: ::core::option::Option<::prost::bytes::Bytes>,
}
/// Packed repeated messages for Vec<T> encoding.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BoolVec {
    #[prost(bool, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Int32Vec {
    #[prost(int32, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Int64Vec {
    #[prost(int64, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Uint32Vec {
    #[prost(uint32, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Uint64Vec {
    #[prost(uint64, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FloatVec {
    #[prost(float, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DoubleVec {
    #[prost(double, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<f64>,
}
/// A message which represents a tuple of up to 10 elements.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TupleMessage {
    #[prost(bytes = "bytes", optional, tag = "1")]
    pub t0: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "2")]
    pub t1: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub t2: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "4")]
    pub t3: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "5")]
    pub t4: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "6")]
    pub t5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "7")]
    pub t6: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "8")]
    pub t7: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "9")]
    pub t8: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "10")]
    pub t9: ::core::option::Option<::prost::bytes::Bytes>,
}
