[package]
name = "acktor-macros"
description = "Internal macros for the acktor actor framework"
version = "1.0.2"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["observer", "debug-trace"]
debug-trace = ["dep:tracing"]
observer = ["dep:tokio", "dep:tracing"]

[dependencies]
tokio = { version = "1.37", features = ["sync"], optional = true }
tracing = { version = "0.1", optional = true }
