[package]
name = "cactor"
version = "1.0.0"
description = "Pure-Rust Actor Framework Built on Tokio Runtime"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
exclude = ["examples/*", "tests/*"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
derive = ["dep:cactor-derive"]
tokio-tracing = ["tokio/tracing"]
bottleneck-warning = []

[dependencies]
futures-util = "0.3"
rustc-hash = "2.1"
tokio = { version = "1.37", features = ["macros", "rt", "sync", "time"] }
tracing = "0.1"

cactor-derive = { workspace = true, optional = true }
cactor-macros = { workspace = true }

[dev-dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
pretty_assertions = "1.4"
