syntax = "proto3";

import "actor_message.proto";
import "node_message.proto";

package ipc_message;

// IPC message.
message IpcMessage {
  oneof message {
    // A message which is used to communicate with remote actors.
    actor_message.ActorMessage actor_message = 1;
    // A message which is used as the response of an `ActorMessage`.
    actor_message.ActorMessageResponse actor_message_response = 2;
    // A message which is used to communicate with remote nodes directly.
    node_message.NodeMessage node_message = 3;
    // A message which is used as the response of a `NodeMessage`.
    node_message.NodeMessageResponse node_message_response = 4;
  }
}
