syntax = "proto3";

package node_message;

// A message which is used to create a new actor in the remote node.
message CreateActor {
  // The label of the actor.
  string label = 1;
  // The type of the actor.
  string type = 2;
  // The config of the actor.
  string config = 3;
  // The tag to be used in the reply.
  uint64 tag = 4;
}

// A message which is used to get the index of a remote actor by its label.
message GetActor {
  // The label of the actor.
  string label = 1;
  // The tag to be used in the reply.
  uint64 tag = 2;
}

// A message which is used to control the remote nodes.
message NodeCommand {
  oneof command {
    // Creates a new actor in the remote node.
    CreateActor create_actor = 1;
    // Gets the index of a remote actor by its label.
    GetActor get_actor = 2;
  }
}

// The result of CreateActor command.
message CreateActorResult {
  // The tag of the message to be replied.
  uint64 tag = 1;
  // The result of the command.
  oneof result {
    // The index of the actor.
    uint64 ok = 2;
    // The error message.
    string err = 3;
  }
}

// The result of GetActor command.
message GetActorResult {
  // The tag of the message to be replied.
  uint64 tag = 1;
  // The result of the command.
  oneof result {
    // The index of the actor.
    uint64 ok = 2;
    // The error message.
    string err = 3;
  }
}

// A message which is used to reply a node command.
message NodeReply {
  oneof reply {
    // The result of CreateActor command.
    CreateActorResult create_actor = 1;
    // The result of GetActor command.
    GetActorResult get_actor = 2;
  }
}

// A message which is used to communicate with remote nodes directly.
message NodeMessage {
  oneof message {
    // Node command.
    NodeCommand command = 1;
    // Reply of a node command.
    NodeReply reply = 2;
  }
}
