syntax = "proto3";

import "utils.proto";

package node_message;

// A message which is used to communicate with the remote node directly.
//
// This message will not be forwarded to any actors in the remote node.
message NodeMessage {
  oneof message {
    // Creates a new actor in the remote node.
    CreateActor create_actor = 1;
    // Gets the index of a remote actor by its label.
    GetActor get_actor = 2;
  }
}

// A message which is used to create a new actor in the remote node.
message CreateActor {
  // The stable type index of the actor type.
  fixed64 type_id = 1;
  // The label of the actor.
  string label = 2;
  // The config of the actor.
  string config = 3;
  // The tag to be used in the message response.
  uint64 tag = 4;
}

// A message which is used to get the index of an actor in the remote node by its actor handle if
// the actor exists.
message GetActor {
  // The actor handle of the actor.
  utils.ActorRef actor = 1;
  // The tag to be used in the message response.
  uint64 tag = 2;
}
